let classes_dict = {
    'ptj-account-details-logout' : "ptj-account-details-logout",
    'ptj-account-handler' : 'ptj-account-handler',
    'ptj-breadcrumbs' : 'ptj-breadcrumbs',
    'ptj-card' : 'ptj-card',
    'ptj-card-row' : 'ptj-card-row',
    'ptj-card-label' : 'ptj-card-label',
    'ptj-card-value' : 'ptj-card-value',
    'ptj-form' : 'ptj-form',
    'ptj-form-title' : 'ptj-form-title',
    'ptj-form-error' : 'ptj-form-error',
    'ptj-form-group' : 'ptj-form-group',
    'ptj-form-submit' : 'ptj-form-submit',
    'ptj-root' : 'ptj-root',
    'ptj-tabs' : 'ptj-tabs',
    'ptj-tabs-card' : 'ptj-tabs-card',
    'ptj-tabs-tab' : 'ptj-tabs-tab',
    'ptj-repo' : 'ptj-repo',
    'ptj-nav' : 'ptj-nav',
    'ptj-nav-link' : 'ptj-nav-link',
    'ptj-single-item' : 'ptj-single-item',
    'ptj-single-item-row' : 'ptj-single-item-row',
    'ptj-single-item-label' : 'ptj-single-item-label',
    'ptj-single-item-value' : 'ptj-single-item-value',
    'ptj-single-item-actions' : 'ptj-single-item-actions',
    'ptj-single-item-children' : 'ptj-single-item-children',
    'ptj-widget-window' : 'ptj-widget-window',
    'ptj-widget-window-header' : 'ptj-widget-window-header',
    'ptj-widget-window-title' : 'ptj-widget-window-title',
    'ptj-widget-window-toggle' : 'ptj-widget-window-toggle',
    'ptj-widget-window-body' : 'ptj-widget-window-body',
    'ptj-repo-header-title' : 'ptj-repo-header-title',
    'ptj-repo-header-actions' : 'ptj-repo-header-actions',
    'ptj-tree' : 'ptj-tree',
    'ptj-form-row' : 'ptj-form-row',
    'ptj-form-input-row' : 'ptj-form-input-row',
    'ptj-form-input-label' : 'ptj-form-input-label',
    'ptj-form-input' : 'ptj-form-input',
    'ptj-table' : 'ptj-table',
    'ptj-table-header' : 'ptj-table-header',
    'ptj-table-header-cell' : 'ptj-table-header-cell',
    'ptj-table-row' : 'ptj-table-row',
    'ptj-table-cell' : 'ptj-table-cell',
    'ptj-table-cell-sortable' : 'ptj-table-cell-sortable',
    'ptj-form-confirm-row' : 'ptj-form-confirm-row',
    'ptj-form-confirm-label' : 'ptj-form-confirm-label',
    'ptj-form-confirm' : 'ptj-form-confirm',
    'ptj-pagination' : 'ptj-pagination',
    'ptj-filter-form' : 'ptj-filter-form',
    'ptj-filter-form-group' : 'ptj-filter-form-group',
    'ptj-filter-form-submit' : 'ptj-filter-form-submit',
    'ptj-form-select-row' : 'ptj-form-select-row',
    'ptj-form-select-label' : 'ptj-form-select-label',
    'ptj-form-select' : 'ptj-form-select',
    'ptj-tree-node' : 'ptj-tree-node',
    'ptj-tree-node-row' : 'ptj-tree-node-row',
    'ptj-selectfields' : 'ptj-selectfields',
    'ptj-selectfields-checkbox' : 'ptj-selectfields-checkbox',
    'ptj-selectfields-label' : 'ptj-selectfields-label',
    'ptj-form-radio-row' : 'ptj-form-radio-row',
    'ptj-form-radio-label' : 'ptj-form-radio-label',
    'ptj-form-radio-option-label' : 'ptj-form-radio-option-label',
    'ptj-checkbox-row' : 'ptj-checkbox-row',
    'ptj-checkbox-label' : 'ptj-checkbox-label',
    'ptj-checkbox' : 'ptj-checkbox',
    'ptj-form-textarea-row' : 'ptj-form-textarea-row',
    'ptj-form-textarea-label' : 'ptj-form-textarea-label',
    'ptj-form-textarea' : 'ptj-form-textarea',
    'ptj-form-asset-row' : 'ptj-form-asset-row',
    'ptj-form-asset-label' : 'ptj-form-asset-label',
    'ptj-form-asset' : 'ptj-form-asset',
    'ptj-progress-bar-wrapper' : 'ptj-progress-bar-wrapper',
    'ptj-progress-bar-holder' : 'ptj-progress-bar-holder',
    'ptj-progress-bar' : 'ptj-progress-bar',
    'ptj-error' : 'ptj-error',
    'ptj-filter-form-time-row' : 'ptj-filter-form-time-row',
    'ptj-filter-form-time-label' : 'ptj-filter-form-time-label',
    'ptj-filter-form-time-1' : 'ptj-filter-form-time-1',
    'ptj-filter-form-time-2' : 'ptj-filter-form-time-2',
    'ptj-filter-form-checkbox-row' : 'ptj-filter-form-checkbox-row',
    'ptj-filter-form-checkbox-label' : 'ptj-filter-form-checkbox-label',
    'ptj-filter-form-checkbox' : 'ptj-filter-form-checkbox',
    'ptj-account-details-logout' : 'ptj-account-details-logout',
    'ptj-accounthandler' : 'ptj-accounthandler',
    'ptj-list' : 'ptj-list'
};

function regClass(name, value) {
    classes_dict[name] = value;
}

function getClass(name) {
    return classes_dict[name];
} 

export default {
    regClass,
    getClass
}